- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/ReivewTag.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/controller/UserController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/PreferRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/PreferResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/entity/Elevation.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/entity/Prefer.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/repository/PreferRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/UserCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/global/auth/CustomUserDetails.java
- src/backend/src/main/java/RunningMachines/R2R/global/auth/CustomUserDetailsService.java
- src/backend/src/main/java/RunningMachines/R2R/global/auth/TokenProvider.java
- src/backend/src/main/java/RunningMachines/R2R/global/exception/ErrorCode.java
- src/backend/src/main/java/RunningMachines/R2R/global/exception/GlobalExceptionHandler.java
> #8 
> 사용자의 선호도 정보(고도/편의시설 여부/자연 여부)를 입력받는다
> BE: [feat] 선호도 조사 #8

- src/backend/build.gradle
- src/backend/src/main/java/RunningMachines/R2R/global/MultipartJackson2HttpMessageConverter.java
- src/backend/src/main/java/RunningMachines/R2R/global/config/S3Config.java
- src/backend/src/main/java/RunningMachines/R2R/global/s3/S3Provider.java
- src/backend/src/main/java/RunningMachines/R2R/global/s3/S3RequestDto.java
- src/backend/src/main/resources/application.yml
> #10 
>  S3에 파일을 저장할 수 있도록 세팅
```
s3Provider.uploadFile(image, S3RequestDto.builder()
.userId(user.getId())
.dirName("profile")
.build());
```
uploadFile 메소드 및 builder를 사용해 파일 업로드
> BE: [feat] S3 연동 #10

- src/backend/src/main/java/RunningMachines/R2R/domain/user/controller/AuthController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserSignupRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/entity/User.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/AuthCommandService.java
> #14 
회원가입 시 프로필 사진을 입력받을 수 있게 함
> BE: [feat] 회원가입 시 프로필 사진 추가 #14

- src/frontend/src/App.tsx
- src/frontend/tailwind.config.js
> #18
> CRA 로 tailwind css를 재적용하였습니다.
> FE: [fix] tailwind css 재적용 #18

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/CourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Course.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/CourseRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/global/config/WebSecurityConfig.java
> #27 
>  코스gpx를 리스트로 받아 s3 및 Course DB에 저장
> BE: [feat] 관리자 코스 등록 구현 #27

- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/PreferResponseDto.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> BE: [refactor] @Setter 제거

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/CourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/GpxResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/GpxQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/global/config/WebSecurityConfig.java
- src/backend/src/main/java/RunningMachines/R2R/global/exception/ErrorCode.java
- src/backend/src/main/java/RunningMachines/R2R/global/s3/S3Provider.java
> #17 
> 저장된 gpx 코스를 받아와서 파일명 및 gpx xml 파일을 열어 파싱해 코스 정보 추출한다.
```
[
{
"fileName": "string",
"waypoints": [
"string"
],
"distance": 0,
"tags": [
"string"
]
}
]
```
> BE: [feat] 코스 정보 반환(나만의 추천 코스) 구현 #17

- src/backend/src/main/java/RunningMachines/R2R/domain/community/board/entity/Board.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> BE: [refactor] 마라톤 게시판 추가 #36

- src/frontend/src/components/community/CommunityList.tsx
- src/frontend/src/components/community/MarathonList.tsx
- src/frontend/src/components/crewMembers/CrewMemberSection.tsx
- src/frontend/src/components/galleryDetail/GalleryContents.tsx
- src/frontend/src/components/home/DistanceRanking.tsx
- src/frontend/src/components/home/FaceRanking.tsx
- src/frontend/src/components/myCrew/ContentsSection.tsx
> FE: [fix] 절대경로 변경 #39

- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/GpxResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/WaypointDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Course.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Review.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Tag.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/UserCourse.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/entity/User.java
- src/backend/src/main/java/RunningMachines/R2R/global/util/GpxParser.java
> #44 
> 웨이포인트 response를 string에서 json으로 수정
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> BE: [feat] 웨이포인트 response 수정 #44

- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/CourseRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
> #50 
> - 코스 정보 반환 시 코스명 반환
> - 태그 값 파싱 수정
> BE: [feat] 추천 코스 반환값 수정 #50

- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/dto/PostShowSimpleResponseDto.java
> BE: [fix] 게시판별 게시글 사진 추가 #36

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/UserCourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/UserCourseRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/UserCourse.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/UserCourseCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/global/exception/ErrorCode.java
- src/backend/src/main/java/RunningMachines/R2R/global/util/GpxFileGenerator.java
> #34 
> timestamp 빼고, 따라뛴 코스 id 추가
```
{
"waypoints": [ 
{
"lat": 0,
"lon": 0,
}
],
"distance": 0,
"duration": 0,
"pace": 0,
"recommendCourse": followRecommendCourse가 true일 때 받아올 추천코스 고유id (코스 추천 때 넘겨줬던 값)
}
```
> BE: [feat] 사용자 러닝 기록 저장 request 수정 #34

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/ReviewController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/ReviewRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/ReviewResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/UserCourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Course.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Review.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/ReviewTag.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/ReviewRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/TagRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/ReviewCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/global/exception/ErrorCode.java
> ex) #67 
> 러닝 후기 작성 구현 (난이도, 태그 선택)
> BE: [feat] 러닝 후기 작성 #67

- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/ReviewCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/entity/Prefer.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/repository/PreferRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/UserCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/global/exception/ErrorCode.java
> ex) #67
> 후기 기반 경사도 선호도 업데이트 (쉬웠으면 한 단계 높이고, 어려웠으면 낮추게 함)
> BE: [feat] 후기 기반 선호도 업데이트 #67

- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/ReviewResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/PreferResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserResponseDto.java
> response dto 필드명 명확하게 정의하도록 수정
> BE: [refactor] response dto 필드명 수정

- src/backend/src/main/java/RunningMachines/R2R/global/exception/ErrorCode.java
- src/backend/src/main/java/RunningMachines/R2R/global/s3/S3Provider.java
> #77 
> S3 한글명 파일 업로드 에러 해결 위해 인코딩 처리 추가
> BE: [fix] S3 한글명 파일 업로드 에러 해결 #77

- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/controller/PostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/dto/PostUpdateRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/entity/Post.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/service/PostCommandService.java
> BE: [feat] 게시글 수정 기능 #36

- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/dto/PostShowSimpleResponseDto.java
> BE: [feat] 미리보기 postId 반환 #36

- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/global/s3/S3Provider.java
> #32 
#89 
> 코스 추천 시 태그 반환 (파싱) 수정
S3 파일데이터->메타데이터 요청하도록 수정
> BE: [fix] 코스 정보 반환 관련 수정 #32, #89

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/entity/CrewPost.java
> BE: [refactor] 게시글 내용 속성 추가 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/repository/CrewUserRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/controller/NoticePostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/dto/NoticePostCreateRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/service/NoticePostCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/repository/CrewPostRepository.java
> BE: [feat] 공지글 작성하기 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/controller/NoticePostController.java
> BE: [refactor] 게시글 작성 엔드포인트 수정 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/ReviewController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/ReviewRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
> #32 
> 코스와 연관된 리뷰 있으면 리뷰들에서 가장 많이 선택된 태그 3개 정렬해 반환
리뷰 없으면 코스파일명 파싱해 태그 반환
_- 빈도수가 동일할 때는 어떻게 반환할 건지 논의 필요_
> BE: [feat] 리뷰 기반 top3 코스 태그 반환 #32

- src/ai/path_naming.py
> AI: [fix] path naming logic 수정 #1

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/controller/CrewController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/dto/CrewCreateCommandDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/entity/Crew.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/entity/CrewProfileImage.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/repository/CrewProfileImageRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/service/CrewCommandService.java
> BE: [feat] 크루 프로필 이미지 추가 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/dto/CrewMainNoticeResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/service/NoticePostQueryService.java
> BE: [feat] 크루 프로필 조회 추가 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/CourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/CourseLikeRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
> #62
>즐겨찾기한 코스 모아서 조회 구현 
추천 코스 반환값에 즐겨찾기 여부 추가
> BE: [feat] 즐겨찾기 코스 조회 #62

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/controller/CrewController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/dto/CrewJoinRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/dto/CrewMemberResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/dto/CrewResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/dto/MemberDetailsDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/repository/CrewUserRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/service/CrewCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/service/CrewQueryService.java
> #83
> 크루 가입, 크루원 조회, 전체 크루 조회
> BE: [feat] 크루 커뮤니티 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/controller/PostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/dto/PostSearchRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/repository/PostRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/service/PostQueryService.java
> BE: [feat] 게시글 키워드 검색 #36

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/repository/CrewUserRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/entity/CrewPost.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/entity/CrewPostLike.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/controller/GalleryPostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/dto/GalleryPostCreateRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/service/GalleryPostCommandService.java
> BE: [feat] 크루 갤러리 글 작성

- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Course.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/ReviewCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/PreferRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/PreferResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/entity/Prefer.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/entity/Preference.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/UserCommandService.java
> BE: [feat] 선호도, 코스 엔티티 수정 #111

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/CourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Course.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/CourseRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/global/s3/S3Provider.java
> #111
> gpx 업로드 시 원본 파일명 그대로 업로드하도록 수정
course 저장 시 원본 파일명을 fileName 컬럼에 저장하도록 수정
fastsAPI에 gpx url 전달할 api 구현
> BE: [fea] 코스 데이터 저장 및 통신 관련 코드 #111

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/controller/GalleryPostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/dto/GalleryPostDetailResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/service/GalleryPostQueryService.java
> BE: [feat] 크루 갤러리 글 상세 조회 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/entity/CrewPost.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/entity/CrewPostImage.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/service/GalleryPostCommandService.java
> #83
> 게시글 이미지 DB에 저장 안되는 문제 해결
> BE: [fix] 갤러리 글 이미지 저장 문제 해결 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/controller/GalleryPostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/dto/GalleryPreviewResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/dto/GallerySimpleResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/service/GalleryPostLikeService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/service/GalleryPostQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/repository/CrewPostLikeRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/repository/CrewPostRepository.java
> BE: [feat] 갤러리 좋아요 #83

- src/backend/build.gradle
- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/CourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Course.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/CourseRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/global/config/WebClientConfig.java
> #111 
> fastApi의 api와 WebClient로 통신하는 위경도 기반 추천 코스 api 구현 및 기존 추천 코스 api와 연관되어 있던 메소드들 전면 수정
파이썬 모델 배포 후 baseurl 수정 필요
> BE: [feat] 코스 추천 파이썬 모델 연동 #111

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/comment/dto/CrewPostCommentRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/comment/dto/CrewPostCommentResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/comment/repository/CrewPostCommentRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/comment/service/CrewPostCommentService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/controller/GalleryPostController.java
> BE: [feat] 갤러리 댓글 달기 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/user/controller/AuthController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/AuthCommandService.java
> BE: [fix] 회원가입 시 토큰 반환 #141

- src/backend/src/main/java/RunningMachines/R2R/domain/user/controller/AuthController.java
> #141
> 회원가입 시 form-data 지정 생략
> BE: [feat] form-data 지정 생략 #141

- src/ai/main.py
- src/ai/runningmachine.py
> #112
> 속도 높이기 위해 코드 수정 및 불필요 코드 제거
> BE: [feat] FastAPI 러닝 코스 추천 최적화 #112

- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/UserCourseRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/home/controller/HomeController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/home/dto/CrewRankResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/home/dto/HomePageResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/home/dto/TodayRunResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/home/service/HomeService.java
> BE: [feat] 메인 화면 구성 #153

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/dto/CrewResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/dto/GallerySimpleResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/service/GalleryPostQueryService.java
> BE: [feat] 반환값 추가 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CoordinateDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/UserCourseRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/entity/Course.java
> #111
> 편의시설 위경도 컬럼 수정 (json리스트로 받을 수 있도록 함)
> BE: [feat] 편의시설 위경도 컬럼 수정 #111

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/CourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/CourseRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
> #156
> 사용자가 많이 뛴 코스 최대 10개 내림차순 정렬
> BE: [feat] 인기 코스 목록 조회 구현 #156

- src/frontend/src/apis/auth.ts
- src/frontend/src/apis/course.ts
- src/frontend/src/apis/crew.ts
- src/frontend/src/apis/running.ts
- src/frontend/src/components/common/AlertModal.tsx
- src/frontend/src/components/common/KakaoMap.tsx
- src/frontend/src/components/record/CourseSection.tsx
- src/frontend/src/components/signup/Step3.tsx
- src/frontend/src/constants/course.ts
- src/frontend/src/constants/preference.ts
- src/frontend/src/hooks/useAuth.ts
- src/frontend/src/hooks/useCourse.ts
- src/frontend/src/hooks/useRunning.ts
- src/frontend/src/pages/Record/RecordPage.tsx
- src/frontend/src/pages/Running/RunningPage.tsx
- src/frontend/src/pages/Signin/SigninPage.tsx
- src/frontend/src/pages/Signup/SIgnupPage.tsx
- src/frontend/src/store/useCourseStore.ts
- src/frontend/src/store/useRunningCourseStore.ts
- src/frontend/src/store/useSelectedCourseStore.ts
- src/frontend/src/types/crew.ts
- src/frontend/src/types/routes.ts
- src/frontend/src/types/running.ts
- src/frontend/src/types/signin.ts
- src/frontend/src/types/signup.ts
> #72 #43 
1. 회원가입, 로그인 완료
2. 선호도 입력 완료
3. 코스 상세설명 추가
4. api 코드 추가
5. 현재 위치 경로 그리기
> FE: [feat] API 연동 및 헌재 위치 경로 그리기 추가

- src/backend/src/main/java/RunningMachines/R2R/domain/course/controller/UserCourseController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/UserCourseRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/UserCourseCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/global/s3/S3Provider.java
- src/backend/src/main/java/RunningMachines/R2R/global/util/GpxFileGenerator.java
> #146
> 러닝 기록 api 위경도 json리스트가 아닌 gpx파일 받도록 수정
> BE: [feat] 러닝 기록 api gpx파일 받도록 수정 #146

- src/backend/src/main/java/RunningMachines/R2R/domain/course/dto/CourseResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
> #111 
> 파일명 파싱해 태그 생성 수정
추천 코스 반환 값에 편의시설(화장실, 편의점) 위경도 추가
> BE: [feat] 추천 코스 반환값 수정 #111

- src/backend/src/main/java/RunningMachines/R2R/domain/course/repository/UserCourseRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/controller/MyPageController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserDistanceDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserDistanceResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserInfoResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserRecentResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserStatsResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/AuthQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/MyPageQueryService.java
> #68
> 유저 정보 조회
달린 거리 월별 조회
최근 러닝 기록 2개 조회
월/주별 러닝 기록 통계
> BE: [feat] 마이페이지 구현

- src/backend/src/main/java/RunningMachines/R2R/domain/user/dto/UserRecentResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/user/service/MyPageQueryService.java
> BE: [feat] 마이페이지 반환값 추가 #68

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/controller/ChatController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/dto/ChatMessageCreateRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/dto/ChatMessageResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/entity/CrewChatImage.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/entity/CrewChatMessage.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/repository/ChatMessageRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/service/ChatCommandService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/chat/service/ChatQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/gallery/controller/GalleryPostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/controller/NoticePostController.java
> BE: [feat] 크루 채팅 보내기 및 조회 기능 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/community/comment/controller/CommentController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/comment/dto/CommentCreateRequestDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/comment/dto/CommentResponseDto.java
> #36 
> 대댓글 엔드포인트 추가 및 반환값 변환
> BE: [feat] 대댓글 엔드포인트 추가 #36

- .gitignore
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/controller/CrewController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/dto/CrewMemberResponseDto.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/service/CrewQueryService.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/controller/NoticePostController.java
- src/backend/src/main/java/RunningMachines/R2R/domain/crew/post/notice/service/NoticePostCommandService.java
> BE: [feat] 크루원 프로필 조회 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/course/service/CourseQueryService.java
> BE: [feat] GPX 파일명 기반 태그 파싱 수정 #32

- src/backend/src/main/java/RunningMachines/R2R/domain/crew/common/controller/CrewController.java
> BE: [fix] 크루 인증사진 에러 해결 #83

- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/repository/PostRepository.java
- src/backend/src/main/java/RunningMachines/R2R/domain/community/post/service/PostQueryService.java
> BE: [feat] 커뮤니티 최신순 정렬 #36

- src/frontend/src/components/common/RunningCalendar.tsx
- src/frontend/src/pages/Mypage/MyPage.jsx
- src/frontend/src/pages/Running/RunningPage.tsx
> FE: [feat] 러닝기록 초에서 분단위 변경
